language: php
    
git:
  depth: 2

matrix:
  include:
    - php: '5.6'
    - php: '7.1'
      env: COVERAGE=true

before_script:
  - composer install --prefer-source --no-interaction

install:
  - if [ $COVERAGE ]; then composer require php-coveralls/php-coveralls; fi
  - if [ $COVERAGE ]; then PHPUNIT_FLAGS="--coverage-clover build/logs/clover.xml"; fi
  - composer require jakub-onderka/php-parallel-lint

script:
  - mkdir -p build/logs
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit $PHPUNIT_FLAGS

after_success:
  - if [ $COVERAGE ]; then travis_retry php vendor/bin/php-coveralls -v; fi


