language: php

git:
  depth: 2

matrix:
  include:
    - php: '5.6'
    - php: '7.1'
      env: COVERAGE=true

before_script:
  - composer install --prefer-source --no-interaction

install:
  - if [[ $COVERAGE == true ]]; then composer require php-coveralls/php-coveralls; fi
  - composer require jakub-onderka/php-parallel-lint

script:
  - mkdir -p build/logs
  - vendor/bin/parallel-lint --exclude vendor .
  - vendor/bin/phpunit --configuration phpunit.xml --coverage-clover build/logs/clover.xml

after_success:
  - if [[ $COVERAGE == true ]]; then travis_retry php vendor/bin/php-coveralls -v; fi


